version: '3'
services:
  server:
    build: server
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - mongo
  mongo:
    image: mongo # Define Mongo version
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
